// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7dIjeKyyCi_W4XewhfQvlKoobmZDXfhg',
    appId: '1:871340027034:web:05db1a19499dffa4b90323',
    messagingSenderId: '871340027034',
    projectId: 'e-commerceapp-877bc',
    authDomain: 'e-commerceapp-877bc.firebaseapp.com',
    storageBucket: 'e-commerceapp-877bc.appspot.com',
    measurementId: 'G-1RKZXK0F81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9JnExj5F6RR8Iu02K3ZobBuf75MR8uvo',
    appId: '1:871340027034:android:61c20efaabb6e8cbb90323',
    messagingSenderId: '871340027034',
    projectId: 'e-commerceapp-877bc',
    storageBucket: 'e-commerceapp-877bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYG0F75mD3tiTTOw47ethlOZX9Pm71Lgc',
    appId: '1:871340027034:ios:16f6dd7f14f06940b90323',
    messagingSenderId: '871340027034',
    projectId: 'e-commerceapp-877bc',
    storageBucket: 'e-commerceapp-877bc.appspot.com',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYG0F75mD3tiTTOw47ethlOZX9Pm71Lgc',
    appId: '1:871340027034:ios:6bf5c7b7dfa6cbefb90323',
    messagingSenderId: '871340027034',
    projectId: 'e-commerceapp-877bc',
    storageBucket: 'e-commerceapp-877bc.appspot.com',
    iosBundleId: 'com.example.hello.RunnerTests',
  );
}
